package vista;

import controlador.ControladorVistaMetodoGrafico;
import javax.swing.table.DefaultTableModel;
import modelo.ModeloVistaMetodoGrafico;

public class VistaMetodoGrafico extends javax.swing.JPanel {

    /**
     * Creates new form VistaMetodoGrafico
     */
    public VistaMetodoGrafico() {
        initComponents();

        ModeloVistaMetodoGrafico modelo = new ModeloVistaMetodoGrafico(this);

        ControladorVistaMetodoGrafico controlador = new ControladorVistaMetodoGrafico(modelo);

        setControlador(controlador);

        //Configuración por defecto de la vista
        btnCalcular.setVisible(true);
        txtResultado.setVisible(false);
        lblResultado.setVisible(false);

    }

    public void vaciarTabla() {
        DefaultTableModel model = (DefaultTableModel) tablaRestricciones.getModel();
        model.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupObjetivo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        radBtnMaximizar = new javax.swing.JRadioButton();
        radBtnMinimizar = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtCoeficienteX1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtX1Restriccion = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        scrollPTablaRestricciones = new javax.swing.JScrollPane();
        tablaRestricciones = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtCoeficienteX2 = new javax.swing.JTextField();
        btnEliminarRestriccion = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtX2Restriccion = new javax.swing.JTextField();
        comboBoxSimbolo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtLadoDerecho = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        scrollGrafica = new javax.swing.JScrollPane();
        panelGrafica = new javax.swing.JPanel();
        txtResultado = new javax.swing.JLabel();
        lblResultado = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();

        setBackground(new java.awt.Color(236, 239, 241));

        jPanel1.setBackground(new java.awt.Color(181, 210, 230));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        btnGroupObjetivo.add(radBtnMaximizar);
        radBtnMaximizar.setForeground(new java.awt.Color(0, 0, 0));
        radBtnMaximizar.setText("Maximizar");
        radBtnMaximizar.setToolTipText("");

        btnGroupObjetivo.add(radBtnMinimizar);
        radBtnMinimizar.setForeground(new java.awt.Color(0, 0, 0));
        radBtnMinimizar.setText("Minimizar");

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText(" Coeficiente X1");

        txtCoeficienteX1.setBackground(new java.awt.Color(204, 204, 204));
        txtCoeficienteX1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Restricciones");

        txtX1Restriccion.setBackground(new java.awt.Color(204, 204, 204));
        txtX1Restriccion.setForeground(new java.awt.Color(0, 0, 0));
        txtX1Restriccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtX1RestriccionActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tablaRestricciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "X1", "X2", "Símbolo", "Valor"
            }
        ));
        scrollPTablaRestricciones.setViewportView(tablaRestricciones);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Coeficiente X2");
        jLabel3.setToolTipText("");

        txtCoeficienteX2.setBackground(new java.awt.Color(204, 204, 204));
        txtCoeficienteX2.setForeground(new java.awt.Color(0, 0, 0));

        btnEliminarRestriccion.setText("Eliminar");
        btnEliminarRestriccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Función Z = aX1+ bX2");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText(" Coeficiente X1");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Coeficiente X2");
        jLabel6.setToolTipText("");

        txtX2Restriccion.setBackground(new java.awt.Color(204, 204, 204));
        txtX2Restriccion.setForeground(new java.awt.Color(0, 0, 0));

        comboBoxSimbolo.setBackground(new java.awt.Color(204, 204, 204));
        comboBoxSimbolo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        comboBoxSimbolo.setForeground(new java.awt.Color(0, 0, 0));
        comboBoxSimbolo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<=", ">=" }));
        comboBoxSimbolo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Símbolo");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Lado Derecho");

        txtLadoDerecho.setBackground(new java.awt.Color(204, 204, 204));
        txtLadoDerecho.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCoeficienteX1)
                            .addComponent(txtCoeficienteX2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtX2Restriccion, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtX1Restriccion, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtLadoDerecho, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(comboBoxSimbolo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(radBtnMaximizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radBtnMinimizar)))
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollPTablaRestricciones, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAgregar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarRestriccion)
                .addGap(17, 17, 17))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radBtnMaximizar)
                    .addComponent(radBtnMinimizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCoeficienteX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCoeficienteX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtX1Restriccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtX2Restriccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxSimbolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLadoDerecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarRestriccion)
                    .addComponent(btnAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPTablaRestricciones, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnCalcular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCalcular.setText("Calcular");

        scrollGrafica.setBackground(new java.awt.Color(204, 204, 204));

        panelGrafica.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout panelGraficaLayout = new javax.swing.GroupLayout(panelGrafica);
        panelGrafica.setLayout(panelGraficaLayout);
        panelGraficaLayout.setHorizontalGroup(
            panelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 747, Short.MAX_VALUE)
        );
        panelGraficaLayout.setVerticalGroup(
            panelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        scrollGrafica.setViewportView(panelGrafica);

        txtResultado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtResultado.setForeground(new java.awt.Color(0, 0, 0));
        txtResultado.setText("Resultado:");

        lblResultado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblResultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setActionCommand("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                        .addGap(71, 71, 71)
                        .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResultado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtX1RestriccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtX1RestriccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtX1RestriccionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnCalcular;
    public javax.swing.JButton btnEliminarRestriccion;
    public javax.swing.ButtonGroup btnGroupObjetivo;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JComboBox<String> comboBoxSimbolo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField lblResultado;
    public javax.swing.JPanel panelGrafica;
    public javax.swing.JRadioButton radBtnMaximizar;
    private javax.swing.JRadioButton radBtnMinimizar;
    public javax.swing.JScrollPane scrollGrafica;
    private javax.swing.JScrollPane scrollPTablaRestricciones;
    public javax.swing.JTable tablaRestricciones;
    public javax.swing.JTextField txtCoeficienteX1;
    public javax.swing.JTextField txtCoeficienteX2;
    public javax.swing.JTextField txtLadoDerecho;
    public javax.swing.JLabel txtResultado;
    public javax.swing.JTextField txtX1Restriccion;
    public javax.swing.JTextField txtX2Restriccion;
    // End of variables declaration//GEN-END:variables

    public void setControlador(ControladorVistaMetodoGrafico controlador) {

        btnCalcular.addActionListener(controlador);
        btnAgregar.addActionListener(controlador);
        btnEliminarRestriccion.addActionListener(controlador);
        btnLimpiar.addActionListener(controlador);

    }

}
